spring:
  datasource:
    url: jdbc:oracle:thin:@//10.100.30.36:1521/ORCLPDB1
    username: data_market
    password: eNao@123.
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
framework:
  infra:
    security:
      jwt:
        secret: "lab-application-secret-key-min-32-characters"
        ttl-seconds: 8300
